# See https://pre-commit.com/ for usage and config
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
            -   id: check-yaml
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        # Ruff version.
        rev: v0.9.6
        hooks:
            # Run the linter.
            -   id: ruff
                args: [ --fix ]
            # Run the formatter.
            -   id: ruff-format
    -   repo: local
        hooks:
            -   id: mypy
                name: mypy
                stages: [ commit ]
                language: system
                entry: pipenv run mypy
                types: [ python ]
                require_serial: true

            -   id: pytest
                name: pytest
                stages: [ commit ]
                language: system
                entry: pipenv run pytest
                types: [ python ]
                pass_filenames: false

            -   id: pytest-cov
                name: pytest
                stages: [ push ]
                language: system
                entry: pipenv run pytest --cov --cov-fail-under=100
                types: [ python ]
                pass_filenames: false
