name: Code Quality

on:
  push:
    branches:
      - '*'

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup Python
                uses: actions/setup-python@v1
                with:
                    python-version: '{{cookiecutter.python_version}}'

            -   name: Install dependencies with pipenv
                run: |
                    pip install pipenv
                    pipenv install --deploy --dev

            -   uses: pre-commit/action@v3.0.0
